version: "3"

tasks:
  fix:
    desc: Format nginx Go sources
    cmds:
      - task -d ./nginx fix

  validate:
    desc: Run nginx Go tests
    cmds:
      - task -d ./nginx validate

  test:
    desc: Run nginx generator unit tests
    cmds:
      - task -d ./nginx test
