version: 1

http:
  redirect_to_https: true

fallback:
  status: 404

shared_rewrites:
  - id: imgproxy-relative
    hosts:
      - apex
      - blog
      - sea-battle
    match_type: regex
    match: "^/cdn/image/relative/(16|32|48|64|96|128|256|384|450|530|640|750|828|1080|1200|1920|2048|3840)/(.*)$"
    rewrite: "/unsafe/width:$1/plain/http://cms:3000/$2"
    upstream: "imgproxy:8080"

  - id: imgproxy-blog
    hosts:
      - apex
      - blog
      - sea-battle
    match_type: regex
    match: "^/cdn/image/blog/(16|32|48|64|96|128|256|384|450|530|640|750|828|1080|1200|1920|2048|3840)/(.*)$"
    rewrite: "/unsafe/width:$1/plain/http://blog:8080/$2"
    upstream: "imgproxy:8080"

  - id: imgproxy-s3
    hosts:
      - apex
      - blog
      - sea-battle
    match_type: regex
    match: "^/cdn/image/s3/(16|32|48|64|96|128|256|384|450|530|640|750|828|1080|1200|1920|2048|3840)/(.*)$"
    rewrite: "/unsafe/width:$1/plain/http://minio1:9000/cms/$2"
    upstream: "imgproxy:8080"

routes:
  - id: root
    host: apex
    locations:
      - match_type: prefix
        match: /
        upstream: "cms:3000"

  - id: www-redirect
    host: www
    redirect:
      to_host: apex
      status: 301

  - id: blog
    host: blog
    locations:
      - match_type: prefix
        match: /
        upstream: "blog:8080"

  - id: sea-battle
    host: sea-battle
    locations:
      - match_type: exact
        match: /api
        upstream: "sea-battle:8080"
      - match_type: prefix
        match: /api/
        upstream: "sea-battle:8080"
      - match_type: prefix
        match: /
        upstream: "sea-battle-client:8080"

  - id: l-you
    host: l-you
    locations:
      - match_type: prefix
        match: /
        upstream: "l-you:3000"

  - id: lovely-eye
    host: s
    locations:
      - match_type: prefix
        match: /
        upstream: "lovely-eye:8080"

  - id: watcharr
    host: tv
    locations:
      - match_type: prefix
        match: /
        upstream: "watcharr:3080"

  - id: vigil
    host: board
    locations:
      - match_type: prefix
        match: /
        upstream: "vigil:8080"

  - id: notes
    host: notes
    locations:
      - match_type: prefix
        match: /
        upstream: "memos:5230"

  - id: whoami
    host: whoami
    locations:
      - match_type: prefix
        match: /
        upstream: "whoami:80"
