package routesgen

import (
	"bytes"
	"embed"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

const (
	generatedHeader  = "# Code generated by routesgen. DO NOT EDIT.\n# Source: routes.yml.\n\n"
	projectDomainVar = "${PROJECT_DOMAIN}"
	apexHostToken    = "apex"
)

var (
	hostTokenPattern = regexp.MustCompile(`^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$`)
	redirectStatuses = map[int]struct{}{
		301: {},
		302: {},
		307: {},
		308: {},
	}
)

//go:embed templates/*.tmpl
var renderTemplateFS embed.FS

var renderTemplates = template.Must(template.ParseFS(renderTemplateFS, "templates/*.tmpl"))

type Config struct {
	Version        int             `yaml:"version"`
	HTTP           HTTPConfig      `yaml:"http"`
	Fallback       FallbackConfig  `yaml:"fallback"`
	SharedRewrites []SharedRewrite `yaml:"shared_rewrites"`
	Routes         []Route         `yaml:"routes"`
}

type HTTPConfig struct {
	RedirectToHTTPS bool `yaml:"redirect_to_https"`
}

type FallbackConfig struct {
	Status int `yaml:"status"`
}

type SharedRewrite struct {
	ID        string   `yaml:"id"`
	Hosts     []string `yaml:"hosts"`
	MatchType string   `yaml:"match_type"`
	Match     string   `yaml:"match"`
	Rewrite   string   `yaml:"rewrite"`
	Upstream  string   `yaml:"upstream"`
}

type Route struct {
	ID        string     `yaml:"id"`
	Host      string     `yaml:"host"`
	Redirect  *Redirect  `yaml:"redirect"`
	Locations []Location `yaml:"locations"`
}

type Redirect struct {
	ToHost string `yaml:"to_host"`
	Status int    `yaml:"status"`
}

type Location struct {
	MatchType string   `yaml:"match_type"`
	Match     string   `yaml:"match"`
	Rewrite   string   `yaml:"rewrite"`
	Includes  []string `yaml:"includes"`
	Upstream  string   `yaml:"upstream"`
}

type headerTemplateData struct {
	GeneratedHeader string
}

type routeTemplateData struct {
	GeneratedHeader string
	ServerName      string
	Redirect        *redirectTemplateData
	LocationBlocks  []string
}

type redirectTemplateData struct {
	Status int
	Target string
}

type fallbackTemplateData struct {
	GeneratedHeader string
	Status          int
}

func LoadConfig(path string) (Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Config{}, fmt.Errorf("read config: %w", err)
	}

	return ParseConfig(data)
}

func ParseConfig(data []byte) (Config, error) {
	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return Config{}, fmt.Errorf("parse routes.yml: %w", err)
	}

	if err := ValidateConfig(cfg); err != nil {
		return Config{}, err
	}

	return cfg, nil
}

func ValidateConfig(cfg Config) error {
	var errs []error

	if cfg.Version != 1 {
		errs = append(errs, fmt.Errorf("version must be 1"))
	}
	if cfg.Fallback.Status < 400 || cfg.Fallback.Status > 599 {
		errs = append(errs, fmt.Errorf("fallback.status must be between 400 and 599"))
	}
	if len(cfg.Routes) == 0 {
		errs = append(errs, fmt.Errorf("routes must not be empty"))
	}

	seenIDs := make(map[string]struct{})
	seenHosts := make(map[string]struct{})

	for _, rewrite := range cfg.SharedRewrites {
		if rewrite.ID == "" {
			errs = append(errs, fmt.Errorf("shared rewrite id must not be empty"))
		} else if err := ensureUniqueID(seenIDs, rewrite.ID); err != nil {
			errs = append(errs, err)
		}

		if len(rewrite.Hosts) == 0 {
			errs = append(errs, fmt.Errorf("shared rewrite %q must target at least one host", rewrite.ID))
		}

		hostSet := make(map[string]struct{})
		for _, host := range rewrite.Hosts {
			if !validHostToken(host) {
				errs = append(errs, fmt.Errorf("shared rewrite %q has invalid host %q", rewrite.ID, host))
			}
			if _, exists := hostSet[host]; exists {
				errs = append(errs, fmt.Errorf("shared rewrite %q repeats host %q", rewrite.ID, host))
			}
			hostSet[host] = struct{}{}
		}

		if rewrite.MatchType != "regex" {
			errs = append(errs, fmt.Errorf("shared rewrite %q match_type must be regex", rewrite.ID))
		}
		if rewrite.Match == "" {
			errs = append(errs, fmt.Errorf("shared rewrite %q match must not be empty", rewrite.ID))
		} else if err := compileRegex(rewrite.Match); err != nil {
			errs = append(errs, fmt.Errorf("shared rewrite %q invalid regex: %w", rewrite.ID, err))
		}
		if rewrite.Rewrite == "" {
			errs = append(errs, fmt.Errorf("shared rewrite %q rewrite must not be empty", rewrite.ID))
		}
		if err := validateUpstream(rewrite.Upstream, fmt.Sprintf("shared rewrite %q", rewrite.ID)); err != nil {
			errs = append(errs, err)
		}
	}

	for _, route := range cfg.Routes {
		if route.ID == "" {
			errs = append(errs, fmt.Errorf("route id must not be empty"))
		} else if err := ensureUniqueID(seenIDs, route.ID); err != nil {
			errs = append(errs, err)
		}

		if !validHostToken(route.Host) {
			errs = append(errs, fmt.Errorf("route %q has invalid host %q", route.ID, route.Host))
		} else if _, exists := seenHosts[route.Host]; exists {
			errs = append(errs, fmt.Errorf("host %q is defined more than once", route.Host))
		} else {
			seenHosts[route.Host] = struct{}{}
		}

		hasRedirect := route.Redirect != nil
		hasLocations := len(route.Locations) > 0
		if hasRedirect == hasLocations {
			errs = append(errs, fmt.Errorf("route %q must define exactly one of redirect or locations", route.ID))
		}

		if route.Redirect != nil {
			if !validHostToken(route.Redirect.ToHost) {
				errs = append(errs, fmt.Errorf("route %q redirect target %q is invalid", route.ID, route.Redirect.ToHost))
			}
			if _, ok := redirectStatuses[route.Redirect.Status]; !ok {
				errs = append(errs, fmt.Errorf("route %q redirect status %d is not supported", route.ID, route.Redirect.Status))
			}
		}

		locationKeys := make(map[string]struct{})
		for _, location := range route.Locations {
			if err := validateLocation(location, fmt.Sprintf("route %q", route.ID)); err != nil {
				errs = append(errs, err)
			}

			key := location.MatchType + "\x00" + location.Match
			if _, exists := locationKeys[key]; exists {
				errs = append(errs, fmt.Errorf("route %q repeats %s match %q", route.ID, location.MatchType, location.Match))
			}
			locationKeys[key] = struct{}{}
		}
	}

	if len(errs) > 0 {
		return errors.Join(errs...)
	}

	return nil
}

func GeneratedRouteFilenames(cfg Config) []string {
	files := make([]string, 0, len(cfg.Routes)+2)
	if cfg.HTTP.RedirectToHTTPS {
		files = append(files, routeTemplateName(1, "http-redirect"))
	}
	for i, route := range cfg.Routes {
		files = append(files, routeTemplateName(i+10, route.ID))
	}
	files = append(files, routeTemplateName(99, "default"))
	return files
}

func GenerateOutputs(cfg Config) (map[string]string, error) {
	outputs := make(map[string]string, len(cfg.Routes)+2)
	if cfg.HTTP.RedirectToHTTPS {
		rendered, err := renderHTTPRedirect()
		if err != nil {
			return nil, err
		}
		outputs[routeTemplateName(1, "http-redirect")] = rendered
	}
	for i, route := range cfg.Routes {
		rendered, err := renderRoute(route, matchingRewrites(cfg.SharedRewrites, route.Host))
		if err != nil {
			return nil, err
		}
		outputs[routeTemplateName(i+10, route.ID)] = rendered
	}
	renderedFallback, err := renderFallback(cfg.Fallback.Status)
	if err != nil {
		return nil, err
	}
	outputs[routeTemplateName(99, "default")] = renderedFallback

	return outputs, nil
}

func routeTemplateName(order int, name string) string {
	return filepath.Base(fmt.Sprintf("%02d-%s.conf.template", order, sanitizeFileName(name)))
}

func renderHTTPRedirect() (string, error) {
	return executeTemplate("http_redirect.tmpl", headerTemplateData{
		GeneratedHeader: generatedHeader,
	})
}

func renderRoute(route Route, rewrites []SharedRewrite) (string, error) {
	data := routeTemplateData{
		GeneratedHeader: generatedHeader,
		ServerName:      renderHost(route.Host),
	}
	if route.Redirect != nil {
		data.Redirect = &redirectTemplateData{
			Status: route.Redirect.Status,
			Target: redirectTarget(route.Redirect.ToHost),
		}
		return executeTemplate("route_server.tmpl", data)
	}

	locationBlocks := make([]string, 0, len(rewrites)+len(route.Locations))
	for _, rewrite := range rewrites {
		locationBlocks = append(locationBlocks, renderLocation(Location{
			MatchType: rewrite.MatchType,
			Match:     rewrite.Match,
			Rewrite:   rewrite.Rewrite,
			Upstream:  rewrite.Upstream,
		}))
	}
	for _, location := range route.Locations {
		locationBlocks = append(locationBlocks, renderLocation(location))
	}
	data.LocationBlocks = locationBlocks

	return executeTemplate("route_server.tmpl", data)
}

func renderFallback(status int) (string, error) {
	return executeTemplate("fallback_server.tmpl", fallbackTemplateData{
		GeneratedHeader: generatedHeader,
		Status:          status,
	})
}

func renderLocation(location Location) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("    %s {\n", renderLocationDirective(location)))
	b.WriteString("        include /etc/nginx/includes/proxy-common.conf;\n")
	for _, includePath := range location.Includes {
		b.WriteString(fmt.Sprintf("        include %s;\n", includePath))
	}
	if location.Rewrite != "" {
		b.WriteString(fmt.Sprintf("        rewrite %s %s break;\n", location.Match, location.Rewrite))
	}
	b.WriteString(fmt.Sprintf("        set $upstream %s;\n", location.Upstream))
	b.WriteString("        proxy_pass http://$upstream;\n")
	b.WriteString("    }\n")
	return b.String()
}

func renderLocationDirective(location Location) string {
	switch location.MatchType {
	case "exact":
		return "location = " + location.Match
	case "prefix":
		if location.Match == "/" {
			return "location /"
		}
		return "location ^~ " + location.Match
	case "regex":
		return "location ~ " + location.Match
	default:
		return "location /"
	}
}

func matchingRewrites(all []SharedRewrite, host string) []SharedRewrite {
	var rewrites []SharedRewrite
	for _, rewrite := range all {
		for _, candidate := range rewrite.Hosts {
			if candidate == host {
				rewrites = append(rewrites, rewrite)
				break
			}
		}
	}
	return rewrites
}

func renderHost(host string) string {
	if host == apexHostToken {
		return projectDomainVar
	}
	return host + "." + projectDomainVar
}

func redirectTarget(host string) string {
	return "https://" + renderHost(host) + "$request_uri"
}

func validHostToken(host string) bool {
	if host == apexHostToken {
		return true
	}
	return hostTokenPattern.MatchString(host)
}

func ensureUniqueID(seen map[string]struct{}, id string) error {
	if _, exists := seen[id]; exists {
		return fmt.Errorf("id %q is defined more than once", id)
	}
	seen[id] = struct{}{}
	return nil
}

func validateLocation(location Location, owner string) error {
	if location.Match == "" {
		return fmt.Errorf("%s has empty match", owner)
	}

	switch location.MatchType {
	case "exact", "prefix":
		if !strings.HasPrefix(location.Match, "/") {
			return fmt.Errorf("%s %s match %q must start with /", owner, location.MatchType, location.Match)
		}
	case "regex":
		if err := compileRegex(location.Match); err != nil {
			return fmt.Errorf("%s invalid regex %q: %w", owner, location.Match, err)
		}
	default:
		return fmt.Errorf("%s has unsupported match_type %q", owner, location.MatchType)
	}

	if location.Rewrite != "" && location.MatchType != "regex" {
		return fmt.Errorf("%s rewrite is only supported for regex matches", owner)
	}
	for _, includePath := range location.Includes {
		if err := validateIncludePath(includePath, owner); err != nil {
			return err
		}
	}

	if err := validateUpstream(location.Upstream, owner); err != nil {
		return err
	}

	return nil
}

func validateUpstream(upstream string, owner string) error {
	if upstream == "" {
		return fmt.Errorf("%s must define upstream", owner)
	}
	if strings.ContainsAny(upstream, " \t\n") {
		return fmt.Errorf("%s upstream %q must not contain whitespace", owner, upstream)
	}
	if !strings.Contains(upstream, ":") {
		return fmt.Errorf("%s upstream %q must include host:port", owner, upstream)
	}
	return nil
}

func validateIncludePath(includePath string, owner string) error {
	if includePath == "" {
		return fmt.Errorf("%s has empty include path", owner)
	}
	if strings.ContainsAny(includePath, "\t\n") {
		return fmt.Errorf("%s include path %q must not contain control characters", owner, includePath)
	}
	return nil
}

func compileRegex(pattern string) error {
	_, err := regexp.Compile(pattern)
	return err
}

func sanitizeFileName(name string) string {
	var b strings.Builder
	lastDash := false
	for _, r := range strings.ToLower(name) {
		isAlphaNum := (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9')
		if isAlphaNum {
			b.WriteRune(r)
			lastDash = false
			continue
		}
		if lastDash {
			continue
		}
		b.WriteByte('-')
		lastDash = true
	}

	sanitized := strings.Trim(b.String(), "-")
	if sanitized == "" {
		return "route"
	}
	return sanitized
}

func executeTemplate(name string, data any) (string, error) {
	var buf bytes.Buffer
	if err := renderTemplates.ExecuteTemplate(&buf, name, data); err != nil {
		return "", fmt.Errorf("render %s: %w", name, err)
	}
	return buf.String(), nil
}
