access_log off;
limit_req_status 429;

error_page 404 /__error_pages/404.html;
error_page 429 /__error_pages/429.html;
error_page 500 /__error_pages/500.html;
error_page 502 /__error_pages/502.html;
error_page 503 /__error_pages/503.html;
error_page 504 /__error_pages/504.html;
error_page 400 401 403 405 406 408 410 411 413 414 415 416 418 421 431 494 495 496 497 /__error_pages/4xx.html;
error_page 501 505 507 /__error_pages/5xx.html;

location ^~ /__error_pages/ {
    internal;
    default_type text/html;
    charset utf-8;
    root /usr/share/nginx/html;
}

add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
add_header X-Content-Type-Options nosniff always;
add_header X-Frame-Options DENY always;
add_header X-XSS-Protection "1; mode=block" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
